server.port: 8888
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IlyaKIA/online-store-property.git
          search-paths: "/rest-online-store/"
          default-label: main